import { gql } from 'urql';
import type { Role } from './auth';

// Hand-written types mirroring backend/schema.gql (generated by the API on boot).
// Swap for graphql-codegen once the schema settles.

export type Tier = 'ai_answer' | 'rag_snippets' | 'faq_floor';
export type Channel = 'console' | 'widget' | 'mcp';
export type Visibility = 'internal' | 'public';
export type DocumentStatus = 'pending' | 'processing' | 'ready' | 'failed';
export type TraceOutcome = 'ok' | 'skipped' | 'rejected' | 'failed';

export interface TraceStep {
  step: string;
  outcome: TraceOutcome;
  detail: string | null;
  ms: number;
}

export interface Workspace {
  id: string;
  name: string;
  widgetKey: string;
  confidenceThreshold: number;
  similarityFloor: number;
}

export interface Membership {
  workspaceId: string;
  name: string;
  role: Role;
}

export interface SystemInfo {
  aiProvider: string;
  chatModel: string;
  embeddingModel: string;
  googleOAuth: boolean;
}

export interface DocumentRow {
  id: string;
  title: string;
  sourceType: string;
  status: DocumentStatus;
  visibility: Visibility;
  chunkCount: number;
  error: string | null;
  mimeType: string | null;
  byteSize: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface Citation {
  chunkId: string;
  documentId: string;
  documentTitle: string;
  snippet: string;
  similarity: number;
}

export interface AnswerResult {
  answerId: string;
  tier: Tier;
  answer: string;
  citations: Citation[];
  confidence: number | null;
  topSimilarity: number | null;
  faqMatchId: string | null;
  trace: TraceStep[];
  latencyMs: number;
}

export interface Faq {
  id: string;
  question: string;
  answer: string;
  keywords: string[];
  visibility: Visibility;
  createdAt: string;
}

export interface Member {
  userId: string;
  email: string;
  displayName: string | null;
  role: Role;
  createdAt: string;
}

export interface Invitation {
  id: string;
  label: string | null;
  role: Role;
  createdAt: string;
  expiresAt: string;
}

export interface ApiToken {
  id: string;
  name: string;
  createdAt: string;
  lastUsedAt: string | null;
  expiresAt: string | null;
}

export interface WidgetConfig {
  widgetKey: string;
  rotatedAt: string;
  publicDocumentCount: number;
  theme: { title: string; greeting: string; primaryColor: string; position: 'left' | 'right' };
}

export interface AnswerLog {
  id: string;
  query: string;
  tier: Tier;
  channel: Channel;
  model: string | null;
  tokensIn: number | null;
  tokensOut: number | null;
  retrievedChunkIds: string[];
  citedChunkIds: string[];
  faqMatchId: string | null;
  confidence: number | null;
  topSimilarity: number | null;
  decisionNote: string | null;
  decisionTrace: TraceStep[];
  latencyMs: number | null;
  createdAt: string;
}

export interface IngestionProgress {
  documentId: string;
  status: 'processing' | 'retrying' | 'ready' | 'failed';
  percent: number;
  chunkCount: number | null;
  error: string | null;
}

const TRACE = 'step outcome detail ms';
const DOCUMENT = 'id title sourceType status visibility chunkCount error mimeType byteSize createdAt updatedAt';

export const SHELL_QUERY = gql`
  query Shell {
    systemInfo { aiProvider chatModel embeddingModel googleOAuth }
    workspace { id name widgetKey confidenceThreshold similarityFloor }
    myWorkspaces { workspaceId name role }
  }
`;

export const CREATE_WORKSPACE = gql`
  mutation CreateWorkspace($name: String!) {
    createWorkspace(input: { name: $name }) { workspaceId name role }
  }
`;

export const DOCUMENTS_QUERY = gql`
  query Documents { documents { ${DOCUMENT} } }
`;

export const INGESTION_DOCUMENTS_QUERY = gql`
  query IngestionDocuments { documents { ${DOCUMENT} } }
`;

export const CREATE_DOCUMENT = gql`
  mutation CreateDocument($input: CreateDocumentFromTextInput!) { createDocumentFromText(input: $input) { ${DOCUMENT} } }
`;

export const SET_VISIBILITY = gql`
  mutation SetVisibility($id: ID!, $visibility: Visibility!) { setDocumentVisibility(id: $id, visibility: $visibility) { ${DOCUMENT} } }
`;

export const RETRY_INGESTION = gql`
  mutation RetryIngestion($id: ID!) { retryIngestion(id: $id) { ${DOCUMENT} } }
`;

export const DELETE_DOCUMENT = gql`
  mutation DeleteDocument($id: ID!) { deleteDocument(id: $id) }
`;

export const INGESTION_PROGRESS = gql`
  subscription IngestionProgress { ingestionProgress { documentId status percent chunkCount error } }
`;

export const ASK_QUESTION = gql`
  mutation AskQuestion($query: String!) {
    askQuestion(query: $query) {
      answerId tier answer confidence topSimilarity faqMatchId latencyMs
      citations { chunkId documentId documentTitle snippet similarity }
      trace { ${TRACE} }
    }
  }
`;

export const UPDATE_LADDER = gql`
  mutation UpdateLadder($input: LadderSettingsInput!) {
    updateLadderSettings(input: $input) { id confidenceThreshold similarityFloor }
  }
`;

const FAQ = 'id question answer keywords visibility createdAt';

export const FAQS_QUERY = gql`
  query Faqs { faqs { ${FAQ} } }
`;

export const CREATE_FAQ = gql`
  mutation CreateFaq($input: FaqInput!) { createFaq(input: $input) { ${FAQ} } }
`;

export const UPDATE_FAQ = gql`
  mutation UpdateFaq($id: ID!, $input: FaqInput!) { updateFaq(id: $id, input: $input) { ${FAQ} } }
`;

export const DELETE_FAQ = gql`
  mutation DeleteFaq($id: ID!) { deleteFaq(id: $id) }
`;

export const MEMBERS_QUERY = gql`
  query Members { members { userId email displayName role createdAt } }
`;

const INVITATION = 'id label role createdAt expiresAt';

export const INVITATIONS_QUERY = gql`
  query Invitations { invitations { ${INVITATION} } }
`;

export const CREATE_INVITATION = gql`
  mutation CreateInvitation($input: CreateInvitationInput!) { createInvitation(input: $input) { token invitation { ${INVITATION} } } }
`;

export const REVOKE_INVITATION = gql`
  mutation RevokeInvitation($id: ID!) { revokeInvitation(id: $id) }
`;

export const ACCEPT_INVITATION = gql`
  mutation AcceptInvitation($token: String!) { acceptInvitation(input: { token: $token }) { workspaceId name role } }
`;

const API_TOKEN = 'id name createdAt lastUsedAt expiresAt';

export const API_TOKENS_QUERY = gql`
  query ApiTokens { apiTokens { ${API_TOKEN} } }
`;

export const CREATE_API_TOKEN = gql`
  mutation CreateApiToken($input: CreateApiTokenInput!) { createApiToken(input: $input) { token apiToken { ${API_TOKEN} } } }
`;

export const REVOKE_API_TOKEN = gql`
  mutation RevokeApiToken($id: ID!) { revokeApiToken(id: $id) }
`;

export const UPDATE_MEMBER_ROLE = gql`
  mutation UpdateMemberRole($input: UpdateMemberRoleInput!) { updateMemberRole(input: $input) { userId email displayName role createdAt } }
`;

export const REMOVE_MEMBER = gql`
  mutation RemoveMember($userId: ID!) { removeMember(userId: $userId) }
`;

export const WIDGET_CONFIG_QUERY = gql`
  query WidgetConfig { widgetConfig { widgetKey rotatedAt publicDocumentCount theme { title greeting primaryColor position } } }
`;

export const UPDATE_WIDGET_THEME = gql`
  mutation UpdateWidgetTheme($input: WidgetThemeInput!) {
    updateWidgetTheme(input: $input) { widgetKey rotatedAt publicDocumentCount theme { title greeting primaryColor position } }
  }
`;

export const ROTATE_WIDGET_KEY = gql`
  mutation RotateWidgetKey { rotateWidgetKey { widgetKey rotatedAt publicDocumentCount theme { title greeting primaryColor position } } }
`;

export const ANSWERS_QUERY = gql`
  query Answers($filter: AnswersFilterInput) {
    answers(filter: $filter) {
      total totalTokens
      tierCounts { tier count }
      items {
        id query tier channel model tokensIn tokensOut retrievedChunkIds citedChunkIds faqMatchId
        confidence topSimilarity decisionNote latencyMs createdAt
        decisionTrace { ${TRACE} }
      }
    }
  }
`;
